#!/usr/bin/with-contenv bash

if [ "${GOACCESS_ENABLED}" = "true" ]; then
    s6-svwait -U /var/run/service/nginx && sleep 0.1
fi

echo "*** loading '${TRAEFIK_CONFIGFILE}' and substituting envs..."
CONFIGFILE="$(mktemp -d -t traefik.XXXX)/traefik.yml"
envsubst < "${TRAEFIK_CONFIGFILE}" > $CONFIGFILE
exec traefik --configFile="$CONFIGFILE"
