#!/usr/bin/with-contenv bash

if [ ! -f /etc/logrotate.d/traefik ]; then
    s6-svc -d .
    exit 0
fi

# delayed startup
s6-svwait -u /var/run/s6/services/traefik && sleep 3s
exec /usr/sbin/crond -f -l ${LOGROTATE_CRON_LOG_LEVEL}
