#!/usr/bin/with-contenv bash

if [ ! "${GOACCESS_ENABLED}" = "true" ]; then
    s6-svc -d .
    exit 0
fi

command="goaccess --no-global-config --config-file=${GOACCESS_CONFIGFILE}"
echo "*** executing => $command"
exec s6-setuidgid abc $command
