#!/usr/bin/with-contenv bash

if [ ! "${GOACCESS_ENABLED}" = "true" ]; then
    s6-svc -d .
    exit 0
fi

ga_basic_opts="
--log-file=${TRAEFIK_ACCESSLOG_FILEPATH}
--log-format=COMMON
--port=7890
--real-time-html
--output=/tmp/goaccess_html/index.html
--db-path=/goaccess/db
--persist
--restore
"

command="goaccess $(echo $ga_basic_opts) ${GOACCESS_USER_OPTS}"
echo "*** executing => $command"
exec s6-setuidgid abc $command
