#!/usr/bin/with-contenv bash

if [ "${GOACCESS_ENABLED}" = "true" ]; then
    until curl -fs -o /dev/null http://localhost:8890 ; do
        sleep 1s
    done
fi

echo "*** loading '${TRAEFIK_CONFIGFILE}' and substituting envs..."
CONFIGFILE="$(mktemp -d -t traefik.XXXX)/traefik.yml"
envsubst < "${TRAEFIK_CONFIGFILE}" > $CONFIGFILE
exec traefik --configFile="$CONFIGFILE"
