#!/usr/bin/with-contenv bash

if [ ! -f "${TRAEFIK_ACCESSLOG_FILEPATH}" ]; then
    echo "*** logrotate disabled: traefik accesslog '${TRAEFIK_ACCESSLOG_FILEPATH}' NOT found!"
    exit 0
fi

cat > /etc/logrotate.d/traefik <<EOL
${TRAEFIK_ACCESSLOG_FILEPATH} {
    ${LOGROTATE_INTERVAL}
    maxsize ${LOGROTATE_MAXSIZE}
    rotate ${LOGROTATE_NROTATE}
    start 1

    missingok
    notifempty

    compress
    delaycompress

    su root root
    create 0644 abc abc

    sharedscripts
    postrotate
        s6-svc -1 /var/run/s6/services/traefik
    endscript
}
EOL

chmod 644 /etc/logrotate.d/traefik
echo "${LOGROTATE_CRON_SCHEDULE} logrotate /etc/logrotate.d/traefik >/dev/null 2>&1" | crontab -
