#!/usr/bin/with-contenv bash

if [ ! "${GOACCESS_ENABLED}" = "true" ]; then
    echo "*** GoAccess disabled: 'GOACCESS_ENABLED=${GOACCESS_ENABLED}'"
    exit 0
fi

if [ ! -f "${TRAEFIK_ACCESSLOG_FILEPATH}" ]; then
    echo "*** GoAccess disabled: '${TRAEFIK_ACCESSLOG_FILEPATH}' NOT found!"
    printf "false" > /var/run/s6/container_environment/GOACCESS_ENABLED
    exit 0
fi

rm -rf \
    /tmp/goaccess_html

mkdir -p \
    /goaccess/db \
    /tmp/goaccess_html

chown -R abc:abc \
    /goaccess \
    /tmp/goaccess_html

echo "*** GoAccess v$(goaccess --version | head -n1 | awk '{print $3}' | sed 's/\.$//') ready!"
