#!/usr/bin/with-contenv bash

cat > /etc/nginx/http.d/default.conf <<EOL
server {
    listen      8080;
    server_name  _;

    absolute_redirect off;

    location / {
        alias  /tmp/goaccess_html/;
        index  index.html index.htm;
    }
}
EOL

mkdir -p \
    /run/nginx
