#!/usr/bin/with-contenv bash

if [ ! "${GOACCESS_ENABLED}" = "true" ]; then
    rm -f /var/run/service/nginx/notification-fd
    exit 0
fi

cat > /etc/nginx/http.d/default.conf <<EOL
server {
    listen      8890;
    server_name  _;

    absolute_redirect off;

    location / {
        alias  /tmp/goaccess_html/;
        index  index.html index.htm;
    }
}
EOL

mkdir -p \
    /run/nginx
